# redirect to Polywork
[[redirects]]
from = "/"
to = "https://timeline.antunes.dev"
status = 302 # using 302, in case one day want to have info here again
force = true

# youtube shortcut
[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/c/CodingMilitia"
status = 302

# blog shortcut
[[redirects]]
from = "/blog"
to = "https://blog.codingmilitia.com"
status = 302

# twitch shortcut
[[redirects]]
from = "/twitch"
to = "https://twitch.tv/joaofbantunes"
status = 302

# twitter shortcut
[[redirects]]
from = "/twitter"
to = "https://twitter.com/joaofbantunes"
status = 302

# linkedin shortcut
[[redirects]]
from = "/linkedin"
to = "https://linkedin.com/in/joaofbantunes"
status = 302

# dev.to shortcut
[[redirects]]
from = "/dev.to"
to = "https://dev.to/joaofbantunes"
status = 302
